// 日本語版・通常2PUページの本文。文言の編集はこのファイルだけで完結する。
// 英語版は render/pickup-en.js を直接編集する(自動同期はしない)。
const fs = require('node:fs');
const path = require('node:path');
const { pct, PYROXENE_PER_PULL, EXCHANGE_PULLS, OVERTIME_LIMIT } = require('../pickup-calc.js');

const ASSETS = path.join(__dirname, '..', '..', 'assets');
const GITHUB_LINK = fs.readFileSync(path.join(ASSETS, 'github-link.html'), 'utf8').trim();

const stone = (pulls) => Math.round(pulls * PYROXENE_PER_PULL).toLocaleString('ja-JP');
const p1 = (value) => `${(value * 100).toFixed(1)}%`;

function verdictLine(result) {
  const { saved, lost, recovered, chargeWins } = result.verdict;
  const verdict = chargeWins
    ? '<b class="gain">呼び出しチャージ優位</b>'
    : '<b class="loss">呼び出しポイント優位</b>';
  return `<p class="verdict">呼び出しチャージは<b class="gain">${stone(saved)}石</b>安くなる代わりに<b class="loss">${Math.round(lost)}文字分減少</b>。<br>文字目的の周回 <u class="tip" tabindex="0" data-tip="${saved.toFixed(1)}連 * (5欠片 + 200文字 / 期待値90連)">${saved.toFixed(1)}連</u> → ${Math.round(recovered)}文字<br>${verdict}</p>`;
}

function outcomeTable(result) {
  const charge = result.charge;
  const point = result.point;
  const overtimeTotal = EXCHANGE_PULLS + point.overtimePulls;
  const rows = [
    `<tr><th>呼出チャージ</th><td data-label="確率">—</td><td data-label="連数">${charge.expectedPulls.toFixed(1)}連</td><td data-label="石">${stone(charge.expectedPulls)}石</td><td data-label="獲得文字">${Math.round(charge.letters)}文字</td></tr>`,
    `<tr><th rowspan="4">呼出ポイント</th><td data-label="確率">${p1(point.branches.both)}</td><td data-label="連数">${EXCHANGE_PULLS}連</td><td data-label="石">${stone(EXCHANGE_PULLS)}石</td><td data-label="獲得文字">${Math.round(point.lettersAt200.both)}文字</td></tr>`,
    `<tr><td data-label="確率">${p1(point.branches.aOnly)}</td><td data-label="連数">${EXCHANGE_PULLS}連</td><td data-label="石">${stone(EXCHANGE_PULLS)}石</td><td data-label="獲得文字">${Math.round(point.lettersAt200.aOnly)}文字</td></tr>`,
    `<tr><td data-label="確率">${p1(point.branches.none)}</td><td data-label="連数">平均${overtimeTotal.toFixed(1)}連</td><td data-label="石">${stone(overtimeTotal)}石</td><td data-label="獲得文字">200文字</td></tr>`,
    `<tr><td data-label="確率">ならして</td><td data-label="連数">${point.expectedPulls.toFixed(1)}連</td><td data-label="石">${stone(point.expectedPulls)}石</td><td data-label="獲得文字">${Math.round(point.letters)}文字</td></tr>`,
  ];
  return `<table><colgroup><col style="width:30%"><col style="width:16%"><col style="width:16%"><col style="width:19%"><col style="width:19%"></colgroup><thead><tr><th>仕様と進め方</th><th>確率</th><th>連数</th><th>石</th><th>獲得文字</th></tr></thead><tbody>${rows.join('')}</tbody></table>`;
}

function pointBlock(result) {
  const b = result.point.branches;
  return `<h3>呼び出しポイント</h3><p>機械的に本命AをPU対象に設定し、引けたら即、相方Bの募集へ。${EXCHANGE_PULLS}連時点の結果だけで分岐。</p><table><colgroup><col style="width:40%"><col style="width:16%"><col style="width:44%"></colgroup><thead><tr><th>${EXCHANGE_PULLS}連時点</th><th>確率</th><th>動き</th></tr></thead><tbody><tr><th>A・Bとも自引き</th><td data-label="確率">${p1(b.both)}</td><td data-label="動き">完了。交換は重複に回して100文字</td></tr><tr><th>A自引きのみ</th><td data-label="確率" class="best">${p1(b.aOnly)}</td><td data-label="動き">交換でB確保、完了</td></tr><tr><th>どちらも無し</th><td data-label="確率">${p1(b.none)}</td><td data-label="動き">交換でAを確保し、残業でBを引き続ける（平均+${result.point.overtimePulls.toFixed(0)}連、${OVERTIME_LIMIT}連時点で出ていなければ交換）</td></tr></tbody></table><p class="note">A・Bとも自引きした後も${EXCHANGE_PULLS}連までは回し切り、その間は0.7%の重複抽選（重複100文字＋50欠片）が走る。残業はBが出た時点で終了。</p>`;
}

function renderPickupHtml(result) {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>通常2PUの新旧比較</title><link rel="stylesheet" href="css/festival.css"></head><body><main><nav class="nav"><a href="./">確率表</a><a href="pickup.html" aria-current="page">通常2PU</a><a href="festival.html">5.5th</a><a href="faq.html">Q&amp;A</a></nav><header class="hero"><div class="header-row"><h1>通常2PUの新旧比較</h1>${GITHUB_LINK}</div><p class="lead">すり抜けに頼れない通常のピックアップ募集で2人を狙う。本命A→相方Bの順に引く前提で、呼び出しポイントと呼び出しチャージを比べる。</p></header>
<section class="panel"><details><summary>計算に使う前提</summary><ul class="rules"><li>PU対象1名の排出率 <b>${pct(result.rates.pu)}</b>。呼び出しチャージはチャージ99で50%、199で100%。</li><li>相方のすり抜けは期待しない。非PU星3の2.3%は100名超の頭割りで、1名あたりは無視できる。</li><li>10連募集を行う度に、50欠片を獲得するものとする。</li><li>初回PUボーナスは<b>PU対象の自引きと呼び出しポイント交換</b>のみ。</li><li>呼び出しポイントは同時開催のPU募集で共通。${EXCHANGE_PULLS}Pで任意の1名と交換。</li><li>本命Aを引けたら即、相方Bの募集へ移る。</li></ul></details></section>
<section class="panel"><h3>結論</h3>${verdictLine(result)}${outcomeTable(result)}<p class="note">呼び出しポイントは自引きと交換が独立に走るぶん獲得文字で上回り、そのぶん降りどきは${EXCHANGE_PULLS}連単位になる。</p>
${pointBlock(result)}</section>
<footer>Generated by scripts/pickup.js</footer></main></body></html>`;
}

module.exports = { renderBody: renderPickupHtml };
